# development
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.125.216.44:3306/insta_db
    username: root
    password: chanee1234!#%Z
    tomcat:
      default-auto-commit: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      use-new-id-generator-mappings: false
#  flyway:
#    locations: classpath:/db/migration
#    baseline-on-migrate: true
#    validateOnMigrate: false
#    baseline-version: 0
#    user: ENC(46QNuFBbD1SvqOwNFdjn2g==)
#    password: ENC(Dhlka+NsTZKKNF7Tdl3NafKShFuNVjwE)
#    enabled: false

logging:
  level:
    org.springframework.orm.jpa.JpaTransaction: debug
    org.hibernate.resource.transaction: debug
    org.hibernate.sql: debug
    org.hibernate.type: trace
    org.springframework: info
  pattern:
    console: "%d{yyyy:MM:dd HH:mm:ss} %-5level %logger{36}:%line - %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"

# 암호화 관련
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: apiKey
